### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by rameau-fr** [duolu/CAROM#1]
Hello,
you truly did a fantastic work, congratulations!
Have you any plans to open your evaluation benchmark?

**Comment by duolu** [comment]
Thanks! We have collected a small dataset using both a differential GPS device and a drone for this paper. The evaluation is not quite comprehensive and we are working on expanding the dataset and design a standard evaluation protocol this year. We will publish another paper about drone-based vehicle tracking, traffic scene reconstruction, and benchmarking dataset this fall or next spring. The new dataset could also be used for training models for other tasks such as 3D pose estimation of vehicles.

**Comment by duolu** [comment]
My colleagues at the Arizona Institute of Automated
Mobility (IAM) released the code at https://github.com/Institute-of-Automated-Mobility/tracking_3d.
