### ISSUE TITLE
code open?

### ISSUE THREAD

**Issue by Andycheng0614** [duolu/CAROM#2]
"The code, videos, tracking results, and reconstruction results areopenly available online 1 ."

so, where is the code?

**Comment by duolu** [comment]
You can contact my colleague Varun Chandra Jammula <vjammula@asu.edu> at Arizona State University (ASU), who maintains the code. The project is managed through the Institute of Automated Mobility (IAM, https://www.azcommerce.com/iam), which is a government agency, and maybe there are regulations on the research outcome. They are actively maintaining the code and using them. I graduated from ASU before this paper was formally published at ICRA 2021, and hence, if you check the ICRA version, this sentence has been removed. Meanwhile, I am exploring alternative vehicle pose estimation methods, which would likely make the classic tangent line method in the paper obsolete. If you would like to collaborate, please contact me directly.

**Comment by duolu** [comment]
My colleagues at the Arizona Institute of Automated
Mobility (IAM) released the code at https://github.com/Institute-of-Automated-Mobility/tracking_3d.
