### ISSUE TITLE
Hi Thanks for presenting your work. Just wondering if you are gonna release the code ?

### ISSUE THREAD

**Issue by Fungungun** [duolu/CAROM#3]

**Comment by duolu** [comment]
You can contact my colleague Varun Chandra Jammula <vjammula@asu.edu> at Arizona State University (ASU), who maintains the code. The project is managed through the Institute of Automated Mobility (IAM, https://www.azcommerce.com/iam), which is a government agency, and maybe there are regulations on the research outcome. They are actively maintaining the code and using them. I graduated from ASU before the paper was formally published.

**Comment by duolu** [comment]
My colleagues at the Arizona Institute of Automated
Mobility (IAM) released the code at https://github.com/Institute-of-Automated-Mobility/tracking_3d.
