### ISSUE TITLE
Code for the CAROM 2021 paper.

### ISSUE THREAD

**Issue by shreejalt** [duolu/CAROM#4]
Hi, 
Thanks for your outstanding work. I was curious if the code especially the calibration code of CAROM(2021) paper is available or I can access it?

**Comment by duolu** [comment]
Hi Shreejal,

Please contact our colleagues at ASU or the Institute of Automated
Mobility. I have graduated and I am not responsible for that project
anymore.


Sincerely,
Duo Lu

**Comment by duolu** [comment]
Hi Shreejal, my colleagues at the Arizona Institute of Automated
Mobility (IAM) released the code at https://github.com/Institute-of-Automated-Mobility/tracking_3d.

**Comment by shreejalt** [comment]
Hi @duolu 
I think the link is not working still. Can you check it once?

**Comment by duolu** [comment]
Hi Shreejal,

Please contact our colleagues at ASU or the Institute of Automated Mobility
(IAM), e.g., the co-author "Varun Chandra Jammula" ***@***.***>. I
have graduated, and I am not responsible for that project anymore. It looks
like you need to request access from IAM.


Sincerely,
Duo Lu
